language: node_js
node_js:
  - "4"
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - sudo apt-get update
  - sudo apt-get install graphicsmagick

before_script:
  - npm run phantom 2>&1 >/dev/null &

script:
  - npm run test
